Cortega3
wkrea/SoDisProyectoClase pull request #37
Opened 2020-06-05 05:30 UTC by carlosorteg

![image](https://user-images.githubusercontent.com/43173004/83840156-7b8ea180-a6c3-11ea-9fbb-13a884dd8577.png)

Profe buenas noches, le adjunto una imagen donde se evidencia que nuevamente me salio el error que tuve la clase pasada, cuando intente hacer el pull. Adjunto también imagen donde se evidencia que el push se ejecuto correctamente, pero no se cual es el problema que tengo al momento de hacer los pull. Le agradezco su ayuda.

![image](https://user-images.githubusercontent.com/43173004/83840269-b98bc580-a6c3-11ea-94fe-2dfca75eaac6.png)

2020-06-05 05:31 UTC, carlosorteg commented
![image](https://user-images.githubusercontent.com/43173004/83840346-f2c43580-a6c3-11ea-8561-fdbfbbd2c2df.png)

2020-06-05 16:51 UTC, wkrea requested changes
Para próximo commit, recuerde:

Agregar el gitignore para NetCore
Eliminar las carpetas bin y obj antes de hacer commit

2020-06-05 16:51 UTC, wkrea commented on src/Supermarket.API/Controllers/CategoriaController.cs
> +
Solo deje un salto de linea entre métodos

2020-06-05 16:51 UTC, wkrea commented on src/Supermarket.API/Dominio/Modelos/Categoria.cs
> +        public IList<Producto> productos {get; set;}
comente todos los atributos y la clase como tal

2020-06-05 16:51 UTC, wkrea commented on src/Supermarket.API/Dominio/Modelos/Producto.cs
> +        public Categoria categoria {get; set;}
comente todos los atributos y la clase como tal

2020-06-05 16:51 UTC, wkrea commented on src/Supermarket.API/Dominio/Repositorios/ICategoriaRepo.cs
> +        ///Permite obtener la informacion de la categoria asociada al identificador pasado por parametro
Sugiero use comentario de tipo ///

2020-06-10 23:26 UTC, wkrea commented
jajjaja lo resolví por fin

2020-06-11 01:37 UTC, merged