Eoviedo1
wkrea/SoDisProyectoClase pull request #38
Opened 2020-06-05 06:14 UTC by stevenor-7

2020-06-05 16:39 UTC, wkrea requested changes
Para próximo commit, recuerde:

* Agregar el gitignore para NetCore
* Eliminar las carpetas bin y obj antes de hacer commit

2020-06-05 16:39 UTC, wkrea commented on src/Supermarket.API/Dominio/Modelos/Categoria.cs
> +         public IList<Producto> productos {get; set;}  //Relacion entre tablas (categorias y productos)
Por favor, comente estos atributos

2020-06-05 16:39 UTC, wkrea commented on src/Supermarket.API/Dominio/Modelos/Categoria.cs
> +    public class Categoria
Por favor, comente la clase

2020-06-05 16:39 UTC, wkrea commented on src/Supermarket.API/Dominio/Modelos/Producto.cs
> +       public   Categoria categoria {get; set;}
Por favor, comente todos estos atributos

2020-06-05 16:39 UTC, wkrea commented on src/Supermarket.API/Dominio/Modelos/Producto.cs
> +    public class Producto
Por favor, comente la clase

2020-06-05 16:39 UTC, wkrea commented on src/Supermarket.API/Dominio/Persistencia/SupermarkerApiContext.cs
> +
Ajuste la indentación y espacios en blanco

2020-06-05 16:39 UTC, wkrea commented on src/Supermarket.API/Dominio/Repositorios/ICategoriaRepo.cs
> +
eliminar espacio en blanco

2020-06-11 23:27 UTC, stevenor-7 commented
Buenas noches Profe Ya agregue las correcciones

2020-06-12 01:39 UTC, closed without merging