Actualización tarea - clase 04/06/2020
wkrea/SoDisProyectoClase pull request #39
Opened 2020-06-05 06:54 UTC by ricardo1204

Creación de modelos para categoría y producto, controller categoría y simulador de BD relacional.

Pdata. Borré bin y obj pero no se por que cuando cargue los archivos en el stand los tomó, los borré, lo actualice y aún así cargó la información, quisiera saber a que se debe eso, tiene q ver con q se cambio de rama en git?, gracias.

2020-06-05 16:11 UTC, wkrea commented
Si Nelson exactamente, porque como en esta oportunidad ud las ha eliminado aparecen el rojo.

El .gitignore está en la rama master ya, de forma que cuando haga fetch upstream en la rama master para actualizarla con la mía, bebería poder ver el archivo ;).

Buen trabajo

2020-06-05 16:13 UTC, wkrea commented
Por si acaso, le agradezco agregue comentarios a las propiedades o atributos de las clases modelos, para que quede bien completa la documentación ;).

y haga ese commit, si quiere agregue el gitignore en ese cambio también ;)

2020-06-05 16:14 UTC, wkrea commented on src/Supermarket.API/Dominio/Modelos/producto.cs
> +        public int id {get; set;}
Comente estas propiedades ;)

2020-06-05 16:14 UTC, wkrea commented on src/Supermarket.API/Dominio/Modelos/categoria.cs
> +        public int id{get; set;}
Comente estas propiedades ;)

2020-06-05 16:15 UTC, wkrea requested changes

2020-06-05 16:15 UTC, wkrea commented on src/Supermarket.API/Dominio/Modelos/categoria.cs
> +        public IList<Producto> productos{get; set;} //Relación entre tablas (categoría y productos)
Comente estas propiedades ;)

2020-06-05 16:15 UTC, wkrea commented on src/Supermarket.API/Dominio/Modelos/producto.cs
> +        public Categoria categoria{get; set;}
Comente estas propiedades ;)

2020-06-05 18:30 UTC, ricardo1204 commented on src/Supermarket.API/Dominio/Modelos/categoria.cs
> +        public IList<Producto> productos{get; set;} //Relación entre tablas (categoría y productos)
Hola profe, es q las propiedades las comente en el comienzo de la clase una a una, como los atributos aún son muy pocos, me pareció más práctico

2020-06-05 18:33 UTC, ricardo1204 commented on src/Supermarket.API/Dominio/Modelos/producto.cs
> +        public Categoria categoria{get; set;}
Para este también las comente en el comienzo de la clase una a una, como lo puede apreciar en el sumary, de igual manera lo haré justo al lado del atributo de ahora en adelante para evitar la confusión, me confirma por fa  si es necesario hacer los cambios, gracias

2020-06-10 07:23 UTC, ricardo1204 commented
Hola profe, ahí agregamos las actualizaciones de la ultima clase, se hicieron los comentarios y se siguieron las instrucciones indicada, feliz día.

2020-06-12 01:06 UTC, wkrea approved these changes

2020-06-12 01:06 UTC, merged